
name = "DashMoleculeSelection"
uuid = "1b08a953-4be3-4667-9a23-1d6e8ebf3f05"
authors = ["DingShinn <dingyubo@dp.tech>"]
version = "1.0.0"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
